#!/bin/bash

## GozJournal
## Quickly create a new journal entry for the day, or if one exists
## edit it by adding the current time at the bottom.
# v.02 - 2018/10/30 - A new journal for each year
# v.01 - 2017/11/26

EDITOR="vim + +startinsert"
EXT="markdown"
YEAR=`date +"%Y"`

if [[ -f ~/.gozjournal ]]; then
    . ~/.gozjournal
else
    echo "No config file, create ~/.gozjournal"
    exit
fi

echo -e "\n`date +'%Y/%m/%d %H:%M'` - ${@}" >> "${DEFAULTFOLDER}/${YEAR}.${EXT}"

if [[ -z $@ ]]; then
    ${EDITOR} "${DEFAULTFOLDER}/${YEAR}.${EXT}"
fi
