#!/bin/bash

## GozNote
## Quickly create notes from the commandline or something like Alfred
## v.02 - 2013/04/29
## v.01 - 2013/01/09

if [ $# -eq 0 ]; then
    echo "GozNote v.02"
    echo "Enter the name of the note as the argument"
    exit
fi

TITLE="$@"
AUTHOR="`whoami`"
DATE=`date +"%Y-%m-%d %H:%M"`
EDITOR="vim + +startinsert"
DEFAULTFOLDER="."
EXT="markdown"
PREPEND=`date +"%Y-%m-%d "`


if [[ ! -f ~/.goznote ]]; then
    echo "No config file, using defaults"
else
    . ~/.goznote
fi



if [[ ! -d ${DEFAULTFOLDER} ]]; then
    echo "${DEFAULTFOLDER} doesn't exist, creating..."
    mkdir "${DEFAULTFOLDER}"
fi

if [[ ! -f ${DEFAULTFOLDER}/${PREPEND}${TITLE}/${TITLE}.${EXT} ]]; then
    echo "Creating directory structure..."
    mkdir "${DEFAULTFOLDER}/${PREPEND}${TITLE}"
    mkdir "${DEFAULTFOLDER}/${PREPEND}${TITLE}/Resources"
    mkdir "${DEFAULTFOLDER}/${PREPEND}${TITLE}/Research"
    echo -n "Creating "
    SLUG=$(echo -n "${TITLE}" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)
    echo -e "Title: ${TITLE}\nAuthor: ${AUTHOR}\nDate: ${DATE}\nSlug: ${SLUG}\nCategory: \nTags: \nStatus: draft\n\n" > "${DEFAULTFOLDER}/${PREPEND}${TITLE}/${TITLE}.${EXT}"
fi

${EDITOR} "${DEFAULTFOLDER}/${PREPEND}${TITLE}/${TITLE}.${EXT}"

