#!/bin/bash

## GozNote
## Quickly create notes from the commandline or something like Alfred
## v.01
## 2013/01/09

if [ ! -f "~/.goznote" ]; then
    echo "No config file, using defaults"
    TITLE="${1}"
    AUTHOR="`whoami`"
    DATE=`date +"%Y-%m-%d"`
    EDITOR="vim + +startinsert"
    DEFAULTFOLDER="."
else
    . ~/.goznote
fi

if [ ! -d "${DEFAULTFOLDER}" ]; then
    echo "${DEFAULTFOLDER} doesn't exist, creating..."
    mkdir "${DEFAULTFOLDER}"
fi

if [ ! -f "${DEFAULTFOLDER}/${TITLE}.markdown" ]; then
    echo -n "Creating "
    echo "${DEFAULTFOLDER}/${TITLE}.markdown"
    echo "% ${TITLE}\n% ${AUTHOR}\n% ${DATE}\n\n" > "${DEFAULTFOLDER}/${TITLE}.markdown"
fi

#${EDITOR} "${DEFAULTFOLDER}/${TITLE}.markdown"

