#!/bin/bash

## GozNote
## Quickly create notes from the commandline or something like Alfred
## v.01
## 2013/01/09

TITLE="$@"
AUTHOR="`whoami`"
DATE=`date +"%Y-%m-%d"`
EDITOR="vim + +startinsert"
DEFAULTFOLDER="."
EXT="markdown"

if [[ ! -f ~/.goznote ]]; then
    echo "No config file, using defaults"
else
    . ~/.goznote
fi

if [[ ! -d ${DEFAULTFOLDER} ]]; then
    echo "${DEFAULTFOLDER} doesn't exist, creating..."
    mkdir "${DEFAULTFOLDER}"
fi

if [[ ! -f ${DEFAULTFOLDER}/${TITLE}.${EXT} ]]; then
    echo -n "Creating "
    echo "${DEFAULTFOLDER}/${TITLE}.${EXT}"
    echo -e "% ${TITLE}\n% ${AUTHOR}\n% ${DATE}\n\n" > "${DEFAULTFOLDER}/${TITLE}.${EXT}"
fi

${EDITOR} "${DEFAULTFOLDER}/${TITLE}.${EXT}"

